#!/usr/bin/env bash

link() {
  from="$HOME/.dotfiles/$1"
  to="$HOME/$2"
  echo "New symlink $to -> $from"
  rm -f $to
  ln -s $from $to
}

# Link necessary files
for file in .{bashrc,gitconfig,vimrc}; do
  link $file $file
done

mkdir -p $HOME/.atom
FILES=.atom/*
for atomFile in $FILES
do
  link $atomFile $atomFile
done

link ".bashrc" ".bash_profile"
