#!/usr/bin/env bash

link() {
  from="$HOME/.dotfiles/$1"
  to="$HOME/$2"
  echo "New symlink $to -> $from"
  rm -f $to
  ln -s $from $to
}

# Link necessary files
for file in .{bash_profile,bashrc,gitconfig,vimrc,profile}; do
  link $file $file
done
