theme = "catppuccin_macchiato"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
nbsp = "all"
tab = "all"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
